config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'start#index'

  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get "bomb",        to: "application#bomb"
  post "report_csp", to: 'application#report_csp'

  # profile
  get   'edit_profile',    to: "start#edit_profile"
  patch 'update_profile',  to: "start#update_profile"

  resources :iconsets do
    resources :icons
  end
  resources :maps do
    resources :layers do
      resources :places
    end
  end

  namespace :admin do
    resources :users
    resources :groups
  end

  namespace :public do
    resources :maps, only: [:show, :index], :defaults => { :format => :json }
  end

end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :group
  has_many :layers

  # call me: Map.by_user(current_user).find(params[:id])
  scope :by_user, lambda { |user|
    where(:group_id => user.group.id) unless user.group.title == 'Admins'
  }

  scope :published, -> { where(published: true) }

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.by_user(current_user)
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @maps = Map.by_user(current_user)
    if @map
      @map_layers = @map.layers
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @map_layers.to_json(:include => { :places => { :methods => [:date, :edit_link] }} ) }
      end
    else
      redirect_to maps_path
    end
  end

  # GET /maps/new
  def new
    @map = Map.new
    @groups = Group.last
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.by_user(current_user).find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:title, :text, :published, :script, :group_id)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.haml
= simple_form_for(@map) do |f|
  .grid-x
    .large-12.cell
      = f.error_notification
  .grid-x
    .large-12.cell
      .form-inputs
        = f.input :title
        = f.input :text
        = f.input :published
        = f.association :group, collection: Group.by_user(current_user), include_blank: false
        = f.input :script
      .form-actions
        %p
          = f.button :submit, :class => "button"
- if admin?
  - if @map.layers.count == 0
    %hr
    = link_to @map, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'button warning' do
      %i.fi.fi-x
      Destroy
  %p.shy Only admins can delete a map. But: You can destroy this map only if you've deleted all places and layers before :#

app/views/maps/edit.html.haml
#form-wrapper
  %h1 Editing map
  = render 'form'
  %hr
  = link_to 'Back', maps_path, :class => 'button'

app/views/maps/index.html.haml
#selection
  .grid-x
    - if @maps.count > 0
      .cell.medium-12
        = simple_form_for :navselector, url: '' do |f|
          .input-group
            .input-group-label
              %i.fi-map.fi-24
            = f.input :id, :collection => @maps.map { |m| ["#{m.title}", "/maps/#{m.id}", :class => "map-#{m.id} input-group-field"] }, :label => false, :selected => @map, :include_blank => 'Select a map...', input_html: {:class => 'nav-selector'}
            .input-group-button
              = link_to new_map_path, :class => 'button secondary', :title => 'Create a new map' do
                %i.fi-plus.fi-24

    - else
      .cell.medium-12
        = link_to new_map_path, :class => 'button info' do
          %i.fi-plus.fi-24
          Create a map

app/views/maps/new.html.haml
#form-wrapper
  %h1 Add map
  = render 'form'

app/views/maps/show.html.haml
#selection{:data => { 'url' => "/maps/#{@map.id}.json" }}
  .grid-x
    .cell.medium-12
      = simple_form_for :navselector, url: '' do |f|
        .input-group
          .input-group-label
            = link_to map_path(@map) do
              %i.fi-map.fi-24

          - icon = '<i class="fi-lock fi-21">'
          - # #{m.published ? '' : icon}
          = f.input :id, :collection => @maps.map { |m| ["#{m.title}", "/maps/#{m.id}", :class => "map-#{m.id} input-group-field"] }, :label => false, :selected => "/maps/#{@map.id}", :include_blank => false, input_html: {:class => 'nav-selector'}
          .input-group-button
            = link_to edit_map_path(@map), :class => 'button secondary' do
              %i.fi-pencil.fi-24

  .grid-x
    .cell.medium-12
      - if @map_layers.count > 0
        = simple_form_for :layer, url: '' do |f|
          .input-group
            .input-group-label
              %i.fi-page-multiple.fi-24
            = f.input "id", :collection => @map_layers.map { |l| ["#{l.title} (#{l.places.count})", "/maps/#{@map.id}/layers/#{l.id}", :class => "layer-#{l.id} input-group-field"] }, :label => false, :include_blank => 'Select a layer...', input_html: {:class => 'nav-selector'}
            .input-group-button
              = link_to new_map_layer_path(@map), :class => 'button secondary', :title => 'Create new layer' do
                %i.fi-plus.fi-24
      - else
        = link_to new_map_layer_path(@map), :class => 'button info' do
          %i.fi-plus
          Create a layer for this map