config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'start#index'

  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get "bomb",        to: "application#bomb"
  post "report_csp", to: 'application#report_csp'

  # profile
  get   'edit_profile',    to: "start#edit_profile"
  patch 'update_profile',  to: "start#update_profile"

  resources :iconsets do
    resources :icons
  end
  resources :maps do
    resources :layers do
      resources :places
    end
  end

  namespace :admin do
    resources :users
    resources :groups
  end

  namespace :public do
    resources :maps, only: [:show, :index], :defaults => { :format => :json }
  end

end

app/models/layer.rb
class Layer < ApplicationRecord
  belongs_to :map
  has_many :places

  scope :published, -> { where(published: true) }
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_action :set_layer, only: [:show, :edit, :update, :destroy]

  protect_from_forgery :except => :show

  # GET /layers
  # GET /layers.json
  def index
    @map = Map.by_user(current_user).find(params[:map_id])
    @layers = @map.layers
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
    @maps = Map.by_user(current_user)
    @map_layers = @map.layers
    @places =  @layer.places
    if params[:remap]
      @place = Place.find(params[:place_id])
    end
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @layer.to_json(:include => { :places => { :methods => [:date, :edit_link] }} ) }
    end
  end

  # GET /layers/new
  def new
    @layer = Layer.new
    @map = Map.by_user(current_user).find(params[:map_id])
  end

  # GET /layers/1/edit
  def edit
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(layer_params)
    @map = Map.by_user(current_user).find(params[:map_id])
    respond_to do |format|
      if @layer.save
        format.html { redirect_to map_path(@map), notice: 'Layer was successfully created.' }
        format.json { render :show, status: :created, location: @layer }
      else
        format.html { render :new }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layers/1
  # PATCH/PUT /layers/1.json
  def update
    respond_to do |format|
      if @layer.update(layer_params)
        format.html { redirect_to map_path(@map), notice: 'Layer was successfully updated.' }
        format.json { render :show, status: :ok, location: @layer }
      else
        format.html { render :edit }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer.destroy
    respond_to do |format|
      format.html { redirect_to map_path(@map), notice: 'Layer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @map = Map.by_user(current_user).find(params[:map_id])
      @layer = Layer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layer_params
      params.require(:layer).permit(:title, :text, :published, :map_id)
    end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.haml
= simple_form_for([@map, @layer]) do |f|
  .grid-x
    .large-12.cell
      = f.error_notification
  .grid-x
    .large-3.cell
      &nbsp;
    .large-6.medium-12.cell
      .form-inputs
        = f.input :title
        = f.input :text
        = f.input :published
        = f.association :map, collection: Map.by_user(current_user), include_blank: false
      .form-actions
        = f.button :submit, :class => "button"
    .large-3.cell
      &nbsp;

app/views/layers/edit.html.haml
#form-wrapper
  %h1 Editing layer
  = render 'form'
  %hr
  = link_to 'Show', [@map, @layer], :class => 'button'

app/views/layers/index.html.haml
#table-wrapper
  %h1
    = link_to map_path(@map) do
      = @map.title


  %table
    %thead
      %tr
        %th Layer
        %th Published?
        %th
        %th

    %tbody
      - @layers.each do |layer|
        %tr
          %td
            %h4
              = link_to map_layer_url(layer.map,layer) do
                = layer.title
                (#{layer.places.count})
            - if layer.text.present?
              %p= layer.text
          %td
            - if layer.published
              %i.fi-check.fi-24
            - else
              %i.fi-x.fi-24
          %td= link_to 'Edit', edit_map_layer_path(@map, layer)
          %td= link_to 'Destroy', map_layer_path(@map, layer), method: :delete, data: { confirm: 'Are you sure?' }

  %p

    = link_to new_map_layer_path(@map), :class=>'button' do
      %i.fi-plus.fi-24
      New Layer

app/views/layers/new.html.haml
#form-wrapper
  %h1 New layer
  = render 'form'

app/views/layers/show.html.haml
- if @map.script && @map.script.present?
  :javascript
    $(document).on('turbolinks:load', function() {
        #{raw(@map.script)}
    });


#selection{:data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}.json", 'map_id' => "#{@map.id}" }}
  .grid-x
    .cell.medium-12
      = simple_form_for :navselector, url: '/maps/', html: { method: :get }  do |f|
        .input-group
          .input-group-label
            = link_to map_path(@map) do
              %i.fi-map.fi-24
          = f.input :id, :collection => @maps.map { |m| ["#{m.title}", "/maps/#{m.id}", :class => "map-#{m.id} input-group-field"] }, :label => false, :selected => "/maps/#{@map.id}", :include_blank => false, input_html: {:class => 'nav-selector'}
          .input-group-button.hide
            = link_to new_map_path, :class => 'button secondary', :title => 'Create a new map' do
              %i.fi-plus.fi-24

  .grid-x
    .cell.medium-12
      - if @map_layers.count > 0
        .input-group
          .input-group-label
            = link_to map_layers_path(@map) do
              %i.fi-page-multiple.fi-24
          = simple_form_for :navselector, url: '', html: { method: :get }  do |f|
            = f.input :id, :collection => @map_layers.map { |l| ["#{l.title} (#{l.places.count})", "/maps/#{@map.id}/layers/#{l.id}", :class => "layer-#{l.id} input-group-field"] }, :label => false, :selected => "/maps/#{@map.id}/layers/#{@layer.id}", :include_blank => false, input_html: {:class => 'nav-selector'}

          .input-group-button.hide
            = link_to new_map_layer_path(@map), :class => 'button secondary', :title => 'Create new layer' do
              %i.fi-plus.fi-24
      - else
        = link_to new_map_layer_path(@map), :class => 'button info' do
          %i.fi-plus
          Create a layer for this map


  .grid-x
    .cell.medium-12
      = simple_form_for :addresslookup, url: '', html: { method: :get, :id => 'addresslookup' } do |f|
        .input-group
          .input-group-label
            = link_to map_layer_places_path(@map,@layer), :title => "Show all places for this layer" do
              %i.fi-marker.fi-24
          = f.input :address, :label => false, :placeholder => 'Name, Street + Number...', input_html: {:class => "address-lookup-field input-group-field", :data => { 'url' => "/maps/#{@map.id}/layers/#{@layer.id}" }}
          .input-group-button
            %button{:id => 'addresslookup_button', :class => 'button secondary', :title => 'Lookup for address'}
              %i.fi-magnifying-glass.fi-24

      - if params[:remap]
        %p#selection-hint
          Type an address or double-click on the map to change the location of
          =link_to edit_map_layer_place_path(@map,@layer,@place) do
            #{@place.title}


      - else
        %p#selection-hint Type an address or double-click on the map to create a place