config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'start#index'

  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get "bomb",        to: "application#bomb"
  post "report_csp", to: 'application#report_csp'

  # profile
  get   'edit_profile',    to: "start#edit_profile"
  patch 'update_profile',  to: "start#update_profile"

  resources :iconsets do
    resources :icons
  end
  resources :maps do
    resources :layers do
      resources :places
    end
  end

  namespace :admin do
    resources :users
    resources :groups
  end

  namespace :public do
    resources :maps, only: [:show, :index], :defaults => { :format => :json }
  end

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users
  has_many :maps

  # call me: Group.by_user(current_user).find(params[:id])
  scope :by_user, lambda { |user|
    where(:id => user.group.id) unless user.group.title == 'Admins'
  }
end

app/controllers/admin/groups_controller.rb
# frozen_string_literal: true

class Admin::GroupsController < ApplicationController
  before_action :set_admin_group, only: [:edit, :update, :destroy]

  def index
    @admin_groups = Group.by_user(current_user)
  end

  def new
    @admin_group = Group.new
  end

  def edit
    unless @admin_group
      redirect_to admin_groups_path, notice: "You can't edit this group."
    end
  end

  def create
    @admin_group = Group.new(admin_group_params)

    respond_to do |format|
      if @admin_group.save
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @admin_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_groups/1
  # PATCH/PUT /admin_groups/1.json
  def update
    respond_to do |format|
      if @admin_group.update(admin_group_params)
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_group }
      else
        format.html { render :edit }
        format.json { render json: @admin_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_groups/1
  # DELETE /admin_groups/1.json
  def destroy
    @admin_group.destroy
    respond_to do |format|
      format.html { redirect_to admin_groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_group
      @admin_group = Group.by_user(current_user).find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_group_params
      params.require(:admin_group).permit(:title)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/_form.html.haml
= simple_form_for [:admin, @admin_group], as: :admin_group do |f|
  .grid-x
    .large-12.cell
      = f.error_notification
  .grid-x
    .large-3.cell
      &nbsp;
    .large-6.medium-12.cell
      .form-inputs
        = f.input :title
      .form-actions
        = f.button :submit, :class => "button"
    .large-3.cell
      &nbsp;

app/views/admin/groups/edit.html.haml
#form-wrapper
  %h1 Editing group
  = render 'form'
  %hr
  = link_to 'All groups', admin_groups_path

app/views/admin/groups/index.html.haml
#table-wrapper
  %h1 Groups

  %table
    %thead
      %tr
        %th Title
        %th Users
        %th Maps
        %th
        %th

    %tbody
      - @admin_groups.each do |group|
        %tr
          %td= group.title
          %td
            - if group.users.count > 0
              %ul
                - group.users.each do |user|
                  %li=user.email

            - else
              No users defined yet
          %td
            - if group.maps.count > 0
              %ul
                - group.maps.each do |map|
                  %li=map.title

            - else
              %p
                = link_to maps_path do
                  No maps defined yet

          %td
            = link_to edit_admin_group_path(group), :class => 'button' do
              %i.fi.fi-pencil
              Edit
          %td
            = link_to admin_group_path(group), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'button warning' do
              %i.fi.fi-x
              Destroy

  %br

  = link_to new_admin_group_path, :class => "button secondary" do
    %i.fi.fi-plus
    New Group

app/views/admin/groups/new.html.haml
#form-wrapper
  %h1 New group

  = render 'form'
  %hr
  = link_to 'All groups', admin_groups_path, :class => 'button'