config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'start#index'

  match 'preferences' => 'preferences#edit', :as => :preferences, via: [:get, :patch]

  get "bomb",        to: "application#bomb"
  post "report_csp", to: 'application#report_csp'

  # profile
  get   'edit_profile',    to: "start#edit_profile"
  patch 'update_profile',  to: "start#update_profile"

  resources :iconsets do
    resources :icons
  end
  resources :maps do
    resources :layers do
      resources :places
    end
  end

  namespace :admin do
    resources :users
    resources :groups
  end

  namespace :public do
    resources :maps, only: [:show, :index], :defaults => { :format => :json }
  end

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :layer

  validates :title,  presence: true

  scope :published, -> { where(published: true) }

  def date
    ApplicationController.helpers.smart_date_display(self.startdate,self.enddate)
  end

  def edit_link
    ApplicationController.helpers.edit_link(self.layer.map.id,self.layer.id,id)
  end

  def full_address
    if self.location.present? && self.address.present?
      if self.location == self.address
        "#{self.location}"
      else
        "#{self.location} #{self.address}"
      end
    elsif self.location.present?
      "#{self.location}"
    else
      "#{self.address}"
    end
  end

  def full_address_with_city
    c = ''
    if self.zip && self.city
      c = ", #{self.zip} #{self.city}"
    end
    "#{self.full_address}#{c}"
  end



end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @layer = Layer.find(params[:layer_id])
    @map = @layer.map
    @places = @layer.places
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @place.location = params[:location]
    @place.address = params[:address]
    @place.zip = params[:zip]
    @place.city = params[:city]
    @place.lat = params[:lat]
    @place.lon = params[:lon]
    @place.layer_id = params[:layer_id]
    @map = Map.by_user(current_user).find(params[:map_id])
    @layer = Layer.find(params[:layer_id])
  end

  # GET /places/1/edit
  def edit

    if params[:lat].present?
      flash[:notice] = "Re-Map: Got new coordinates and address data. Please check all fields and click 'Update place'"
      @old_place = @place.dup
      @place.location = params[:location]
      @place.address = params[:address]
      @place.zip = params[:zip]
      @place.city = params[:city]
      @place.lat = params[:lat]
      @place.lon = params[:lon]
      @place.layer_id = params[:layer_id]
      @map = Map.by_user(current_user).find(params[:map_id])
      @layer = Layer.find(params[:layer_id])
    end
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @layer = Layer.find(@place.layer_id)
    @map = @layer.map

    respond_to do |format|
      if @place.save
        format.html { redirect_to map_layer_url(@map,@layer), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    @layer = @place.layer
    @map = @place.layer.map

    # quirks, because foundation switch generats 'on'/'off' values,
    # rails expect true/false
    # TODO: render this at generating the form
    if params[:place][:published] == 'on'
      params[:place][:published] = true
    else
      params[:place][:published] = false
    end
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to map_layer_url(@map.id,@place.layer.id), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to map_layer_places_path(@map,@layer), notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @map = Map.by_user(current_user).find(params[:map_id])
      @layer = Layer.find(params[:layer_id])
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :teaser, :text, :link, :startdate, :enddate, :lat, :lon, :location, :address, :zip, :city, :country, :published, :imagelink, :layer_id)
    end
end

app/helpers/places_helper.rb
module PlacesHelper



  def edit_link(map_id,layer_id,id)
    " <a href='/maps/#{map_id}/layers/#{layer_id}/places/#{id}/edit' class='button1 tiny1'><i class='fi fi-pencil'></a>"
    # TODO: use link_to instead:
    # html_concat link_to(edit_map_layer_place(map_id, layer_id, id), class: 'button tiny') {
    #    html_tag :i, 'aria-hidden': 'true', class: 'fa fa-pencil'
    #  }

  end

end

app/views/places/_form.html.haml
= simple_form_for([@map,@layer,@place]) do |f|
  .grid-x.grid-padding-x
    .large-3.medium-3.cell
      %h1 Place
      .grid-x
        .small-5.cell
          %p{:title=>"This settings publishes this place on the map!"}
            Publish?
        .small-7.cell
          .switch
            %input{:name=>"place[published]", :class => "switch-input", :id => "place_published", :type => "checkbox", :checked => @place.published }
            %label.switch-paddle{:for=>"place_published"}
              %span.show-for-sr
                Publish
              %span.switch-active{:aria-hidden=>"true"} Yes
              %span.switch-inactive{:aria-hidden=>"true"} No

    .large-7.medium-7.cell

      - if @place.layer.title && params[:action] == 'new'
        %p
          %span.name Layer:
          = link_to map_layer_url(@place.layer.map,@place.layer) do
            = @place.layer.title
          = f.association :layer, as: :hidden
      - else
        = f.association :layer, include_blank: false
      %p
        %span.name Coordinates (Lat/Lon):
        - if @old_place
          #{@old_place.lat[0..4]}/#{@old_place.lon[0..4]}
          \-->
        #{@place.lat[0..4]}/#{@place.lon[0..4]}
        = f.input :lat, as: :hidden
        = f.input :lon, as: :hidden
      %p
        %span.name Address:
        - if @old_place
          = @old_place.full_address
          \-->
        = @place.full_address
    .large-2.medium-2.cell
      - if params[:action] == 'edit'
        %p
          = link_to map_layer_path(@place.layer.map,@place.layer,remap: true, place_id: @place.id), :class =>"button secondary small" do
            Re-Map

  .grid-x.grid-padding-x
    .large-12.cell
      = f.error_notification
      = f.input :title

  .grid-x.grid-padding-x
    .large-6.medium-6.cell
      .form-inputs
        = f.input :startdate
        = f.input :enddate
        = f.input :teaser, :label => 'Text', :input_html => {:rows => 9, class: 'large-text'}


    .large-6.medium-6.cell
      .form-inputs
        = f.input :location, :label => 'Name of Location', :input_html => {:placeholder => 'Name' }
        = f.input :address, :input_html => {:placeholder => 'Street + Number' }
        .grid-x.grid-padding-x
          .small-4.cell
            = f.input :zip
          .small-8.cell
            = f.input :city
        = f.input :link, :label => 'Weblink', :placeholder => 'http://'
        = f.input :imagelink, :input_html => {:placeholder => 'http://' }
  .grid-x.grid-padding-x
    .large-12.cell
      .form-actions
        = f.button :submit, :class => "button"

app/views/places/edit.html.haml
#form-wrapper.large-wrapper
  = link_to map_layer_url(@map,@layer), :class=>"close-button button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x
  = render 'form'

app/views/places/index.html.haml
#table-wrapper
  = link_to map_layer_url(@map,@layer), :class=>"close-button button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x
  %h3
    = link_to map_path(@layer.map) do
      = @layer.map.title
    \>
    = link_to map_layer_path(@layer.map,@layer) do
      = @layer.title
    (#{@places.count})


  %table
    %thead
      %tr
        %th Date
        %th Title/Link
        %th Address
        %th Lat/Lon
        %th Published?
        %th
        %th

    %tbody
      - @places.order(:startdate).each do |place|
        %tr
          %td
            = smart_date_display(place.startdate, place.enddate)
          %td
            %h4= place.title
            %p= place.link
          %td
            = place.location
            %br
            = place.address
            %br
            = place.zip
            = place.city
          %td
            #{place.lat[0..6]}/#{place.lon[0..5]}
          %td
            - if place.published
              %i.fi-check.fi-24
            - else
              %i.fi-lock.fi-24
          %td= link_to 'Edit', edit_map_layer_place_path(place.layer.map,place.layer,place)
          %td= link_to 'Destroy',  map_layer_place_path(place.layer.map,place.layer,place), method: :delete, data: { confirm: 'Are you sure?' }

app/views/places/new.html.haml
#form-wrapper.large-wrapper
  = link_to map_layer_url(@map,@layer), :class=>"close-button button small", "aria-label"=>"Close back",:type=>"button" do
    %span{"aria-hidden"=>"true"}
      %i.fi.fi-x
  = render 'form'

app/views/places/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @place.title
%p
  %b Teaser:
  = @place.teaser
%p
  %b Text:
  = @place.text
%p
  %b Link:
  = @place.link
%p
  %b Startdate:
  = @place.startdate
%p
  %b Enddate:
  = @place.enddate
%p
  %b Lat:
  = @place.lat
%p
  %b Lon:
  = @place.lon
%p
  %b Location:
  = @place.location
%p
  %b Address:
  = @place.address
%p
  %b Zip:
  = @place.zip
%p
  %b City:
  = @place.city
%p
  %b Country:
  = @place.country
%p
  %b Published:
  = @place.published
%p
  %b Layer:
  = @place.layer